FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3.11 python3-pip && rm -rf /var/lib/apt/lists/*

WORKDIR /code
COPY pyproject.toml .
RUN pip install --no-cache-dir .

COPY __init__.py ./inference/__init__.py
COPY app/ ./inference/app/
COPY ml/ ./inference/ml/
ENV PYTHONPATH=/code

EXPOSE 8001
CMD ["uvicorn", "inference.app.main:app", "--host", "0.0.0.0", "--port", "8001"]
